replicaCount: 2

image:
  repository: local/node-express-api
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 4000
  targetPort: 4000

ingress:
  enabled: false
  host: ""

resources: {}

hpa:
  enabled: false
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 60
